# Generated by Django 4.2 on 2025-08-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_booking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveloption',
            name='travel_id',
        ),
    ]
